update metadata
wagumi/sbt pull request #176
Opened 2023-03-25 17:24 UTC by ikisuke

2023-03-25 23:45 UTC, tksohishi requested changes

2023-03-25 23:45 UTC, tksohishi commented on metadata/1000785293852545094.json
> -  "image": "https://apps.wagumi.xyz/sbt/image?userid=1000785293852545094",
新しいサーバに移行しているのでこちらは変更しないようにする必要があります

2023-03-26 02:44 UTC, tksohishi commented on metadata/1000785293852545094.json
> -  "image": "https://apps.wagumi.xyz/sbt/image?userid=1000785293852545094",
.envを
`SBT_IMAGE_URL=https://apps.wagumi.xyz/sbt/image?userid=`
に変更

2023-03-26 07:06 UTC, ikisuke reviewed
@tksohishi 
imageの修正完了いたしました、ご確認の程よろしくお願いいたします！

2023-03-26 08:14 UTC, tksohishi requested changes

2023-03-26 08:14 UTC, tksohishi commented on metadata/1087534717848535112.json
> +<<<<<<< Updated upstream
Merge conflictが残ったまま？

2023-03-26 11:04 UTC, tksohishi commented on metadata/1087534717848535112.json
> +<<<<<<< Updated upstream
これ以外は大丈夫そうですね。IVS那覇のやつはNotionの画像URLの有効期限切れ問題に起因するものかなと思うので、contributionに登録する画像はできる限り外部URLを使用したほうが良さそう？

2023-03-26 16:29 UTC, ikisuke commented on metadata/1087534717848535112.json
> +<<<<<<< Updated upstream
> Merge conflictが残ったまま？

あら、すいません。
こちら修正しました

2023-03-26 16:30 UTC, ikisuke commented on metadata/1087534717848535112.json
> +<<<<<<< Updated upstream
> これ以外は大丈夫そうですね。IVS那覇のやつはNotionの画像URLの有効期限切れ問題に起因するものかなと思うので、contributionに登録する画像はできる限り外部URLを使用したほうが良さそう？

ですねー、Gyazoとかimgurとかって永続するやつだったでしたっけ？
永続するなら、Notionに直接アップするより間に噛ませた方が良さそうだなって思いました。

2023-03-26 22:04 UTC, tksohishi approved these changes
LGTMです！

2023-03-26 22:04 UTC, merged